<?php

namespace TestTask\TodoListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasksRepository extends EntityRepository
{
    /**
     * @param $list_id
     * @return array
     */
    public function getTask($list_id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('c')
            ->from('TodoListBundle:Task',  't')
            ->where('t.list = :list_id')
            ->setParameter('list_id', $list_id)
            ->getQuery()
            ->getResult();

        return $query;
    }

    /**
     * @param $card
     */
    public function saveTask($card)
    {
        $em = $this->getEntityManager();
        $em->persist($card);
        $em->flush();
    }
}
